#!/bin/bash
# Yunohost Script
# Move your photos, and videos from Nextcloud to Photoprism
# by tootbrute

# VARIABLES
current_date=$(date +%Y)/$(date +%m)/

# SCRIPT
echo '# PHOTOPRISM SCRIPT - START'
echo '#'
echo '## START RSYNC ELIAS PHOTOS...'
echo '#### CURRENT DATE IS:' $current_date
photos_import='/home/yunohost.app/nextcloud/data/USERNAME/files/USERNAMEPics/'
photos_src=$photos_import$current_date
echo '##### PHOTO SOURCE DIRECTORY IS:'
echo $photos_src
photos_raid='/mnt/hermes/Pictures/originals/'
photos_dest=$photos_raid$current_date
echo '###### PHOTO DESTINATION DIRECTORY IS:'
echo $photos_dest
echo '####### SENDING FILES WITH RSYNC...'
rsync -avh --mkpath $photos_src $photos_dest
echo '####### END RSYNC ELIAS PHOTOS now INDEX.'
docker exec photoprism photoprism index --cleanup
