#!/bin/bash
# Photoprism Script by tootbrute
#===============================
# This script will:
# - move your photos from your Nextcloud folder to your Photoprism folder
# - re-index the new photos in your Photoprism
#
# VARIABLES
# ex. /2023/03/
year_month=$(date +%Y)/$(date +%m)/
# Where are your photos stored in Nextcloud?
photos_nextcloud='/home/yunohost.app/nextcloud/data/USERNAME/files/Pictures/'
photos_source=$photos_nextcloud$year_month
# Where do you want your photos to go?
photos_raid='/mnt/raid_drive/Pictures/originals/'
photos_destination=$photos_raid$year_month

# SCRIPT BEGIN
rsync -avh --mkpath $photos_source $photos_destination
docker exec photoprism photoprism index --cleanup
