#!/bin/bash
# Restic Backup Script by tootbrute
# ==================================
# Script to backup files on Yunohost https://yunohost.org using restic https://restic.net/
# One backup is on a local RAID backup.
# Another is to an offsite backup server using rest-server https://github.com/restic/rest-server

# Variables
# Set the IP address of Tailscale node for offsite backup
offsite_backup_server=$(tailscale status | grep your_server_tailscale_name | grep -E -o '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')

# Your Username
username=change_to_your_username

# Structure of restic source file
$ cat .restic-info
export RESTIC_REPOSITORY="/mnt/raid/restic-repo/"
export RESTIC_PASSWORD="password-here"
export RESTIC_COMPRESSION="auto"

# Start Script
# =================================
# Loads restic repository name and password
source /home/$username/.restic-info
# Local Backups (some example directories you might want to backup)
restic backup /home/$username/ --tag home_dir
restic backup /home/yunohost.app/nextcloud/data/$username/files/ --tag nextcloud
restic backup /home/yunohost.backup/archives/ --tag yunohost
restic check

# Backup to offsite backup
source /home/$username/.restic-offsite
restic -r rest:http://$offsite_backup_server:8000 backup /mnt/raid/Pictures/ --tag photos
restic -r rest:http://$offiste_backup_server:8000 backup /home/yunohost.app/nextcloud/data/$username/files/ --tag nextcloud
restic -r rest:http://$offsite_backup_server:8000 backup /mnt/raid/Documents/ --tag docs
restic -r rest:http://$offsite_backup_server:8000 check

# Script end

# Setup cron to run this daily
# 59 23 * * * root /home/$username/bin/restic-backup
